version: '3'

services:
  mongo3:
    hostname: mongo3
    image: docker.mofid.dev/mongo:6.0.3
    extra_hosts:
      - "mongo1:172.17.0.1"
      - "mongo2:172.17.0.1"
    ports:
      - 27019:27019
    entrypoint: [ "/usr/bin/mongod", "--config", "/data/config/mongodb.conf", "--bind_ip_all", "--replSet", "dbrs" ]
    volumes:
      - ./.db/mongo3:/data/db
      - ./ssl:/data/ssl
      - ./config:/data/config
      - ./wait-for-mongodb.sh:/scripts/wait-for-mongodb.sh
