version: '3'
services:
  redis-3:
    container_name: "redis-3"
    image: docker.mofid.dev/redis:7-alpine
    network_mode: host
    command: redis-server --slaveof redis-1 6380 --requirepass test --masterauth test --appendonly yes --maxmemory 256mb --port 6382 
    volumes:
      - "./redis.conf:/etc/redis.conf"
      - "./data:/data"

  redis-sentinel3:
    container_name: "redis-sentinel3"
    image: docker.mofid.dev/redis:7-alpine
    network_mode: host
    user: root
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel 
    volumes:
      - "./sentinel_conf:/usr/local/etc/redis"
