version: '3'
services:
  redis-1:
    container_name: "redis-1"
    image: docker.mofid.dev/redis:7-alpine
    network_mode: host
    command: redis-server --requirepass test --appendonly yes --maxmemory 256mb --port 6380 --bind 0.0.0.0
    volumes:
      - "./redis.conf:/etc/redis.conf"
      - "./data:/data"

  redis-sentinel1:
    container_name: "redis-sentinel1"
    image: docker.mofid.dev/redis:7-alpine
    network_mode: host
    user: root
    command: redis-server /usr/local/etc/redis/sentinel.conf --sentinel
    volumes:
      - "./sentinel_conf:/usr/local/etc/redis"
